### PR TITLE
User can delete his account

### PR DESCRIPTION
**Pull request by Runster**
I've added a functionality, which allows the user to delete his account.

### CODE REVIEW

**Comment by Croydon** [comment]
This is way too easy to abuse. One could simply redirect a logged in user to `/user/settings?deleteaccount` and the account would get deleted without any user confirmation.

It should be required to enter the password as confirmation to prevent abuse.

**Comment by Runster** [comment]
Yeah, that's a good point. I have added a password confirmation. 
Additionally it isn't possible for the admin to delete his account.

**Comment by Croydon** [comment]
@Runster Good work so far. However, this feature looks incomplete.
The admin should be able to delete accounts as well. To implement this it would be probably the best to outsource the account deletion logic in a module named `app/module/delete_account.php` and reuse this in the admin user management.
Remember that even for the admin it should be checked that there aren't any accidently deletions.

**Comment by Croydon** [comment]
Merged via 56922bf0efd9ee04bd4b2962c4bd8c3d2d811119 and 729aef287ef3edcad71eeab4b4048a0dfb150329

**Pull request closed without merging**
